// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'player.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1229154124;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xue_hua_video_player',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlayerHandle> crateApiPlayerCreatePlayer({
    required PlatformInt64 engineHandle,
  });

  Future<void> crateApiPlayerDisposePlayer({required PlatformInt64 playerId});

  Future<void> crateApiSimpleInitApp();

  Future<PlatformInt64> crateApiPlayerPlayerDuration({
    required PlatformInt64 playerId,
  });

  Stream<PlayerEvent> crateApiPlayerPlayerEventStream({
    required PlatformInt64 playerId,
  });

  Future<void> crateApiPlayerPlayerPause({required PlatformInt64 playerId});

  Future<void> crateApiPlayerPlayerPlay({required PlatformInt64 playerId});

  Future<PlatformInt64> crateApiPlayerPlayerPosition({
    required PlatformInt64 playerId,
  });

  Future<void> crateApiPlayerPlayerSeek({
    required PlatformInt64 playerId,
    required PlatformInt64 positionMs,
  });

  Future<void> crateApiPlayerPlayerSetLooping({
    required PlatformInt64 playerId,
    required bool looping,
  });

  Future<void> crateApiPlayerPlayerSetMute({
    required PlatformInt64 playerId,
    required bool mute,
  });

  Future<void> crateApiPlayerPlayerSetSource({
    required PlatformInt64 playerId,
    required String uri,
  });

  Future<void> crateApiPlayerPlayerSetSpeed({
    required PlatformInt64 playerId,
    required double speed,
  });

  Future<void> crateApiPlayerPlayerSetVolume({
    required PlatformInt64 playerId,
    required double volume,
  });

  Future<void> crateApiPlayerPlayerStop({required PlatformInt64 playerId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlayerHandle> crateApiPlayerCreatePlayer({
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(engineHandle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_handle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerCreatePlayerConstMeta,
        argValues: [engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerCreatePlayerConstMeta => const TaskConstMeta(
    debugName: "create_player",
    argNames: ["engineHandle"],
  );

  @override
  Future<void> crateApiPlayerDisposePlayer({required PlatformInt64 playerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerDisposePlayerConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerDisposePlayerConstMeta =>
      const TaskConstMeta(debugName: "dispose_player", argNames: ["playerId"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PlatformInt64> crateApiPlayerPlayerDuration({
    required PlatformInt64 playerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerDurationConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerDurationConstMeta =>
      const TaskConstMeta(debugName: "player_duration", argNames: ["playerId"]);

  @override
  Stream<PlayerEvent> crateApiPlayerPlayerEventStream({
    required PlatformInt64 playerId,
  }) {
    final sink = RustStreamSink<PlayerEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_i_64(playerId, serializer);
            sse_encode_StreamSink_player_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiPlayerPlayerEventStreamConstMeta,
          argValues: [playerId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiPlayerPlayerEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: "player_event_stream",
        argNames: ["playerId", "sink"],
      );

  @override
  Future<void> crateApiPlayerPlayerPause({required PlatformInt64 playerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerPauseConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "player_pause", argNames: ["playerId"]);

  @override
  Future<void> crateApiPlayerPlayerPlay({required PlatformInt64 playerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerPlayConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "player_play", argNames: ["playerId"]);

  @override
  Future<PlatformInt64> crateApiPlayerPlayerPosition({
    required PlatformInt64 playerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerPositionConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPositionConstMeta =>
      const TaskConstMeta(debugName: "player_position", argNames: ["playerId"]);

  @override
  Future<void> crateApiPlayerPlayerSeek({
    required PlatformInt64 playerId,
    required PlatformInt64 positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_i_64(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSeekConstMeta,
        argValues: [playerId, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSeekConstMeta => const TaskConstMeta(
    debugName: "player_seek",
    argNames: ["playerId", "positionMs"],
  );

  @override
  Future<void> crateApiPlayerPlayerSetLooping({
    required PlatformInt64 playerId,
    required bool looping,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_bool(looping, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSetLoopingConstMeta,
        argValues: [playerId, looping],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetLoopingConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_looping",
        argNames: ["playerId", "looping"],
      );

  @override
  Future<void> crateApiPlayerPlayerSetMute({
    required PlatformInt64 playerId,
    required bool mute,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_bool(mute, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSetMuteConstMeta,
        argValues: [playerId, mute],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetMuteConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_mute",
        argNames: ["playerId", "mute"],
      );

  @override
  Future<void> crateApiPlayerPlayerSetSource({
    required PlatformInt64 playerId,
    required String uri,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSetSourceConstMeta,
        argValues: [playerId, uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetSourceConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_source",
        argNames: ["playerId", "uri"],
      );

  @override
  Future<void> crateApiPlayerPlayerSetSpeed({
    required PlatformInt64 playerId,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSetSpeedConstMeta,
        argValues: [playerId, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_speed",
        argNames: ["playerId", "speed"],
      );

  @override
  Future<void> crateApiPlayerPlayerSetVolume({
    required PlatformInt64 playerId,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          sse_encode_f_64(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerSetVolumeConstMeta,
        argValues: [playerId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_volume",
        argNames: ["playerId", "volume"],
      );

  @override
  Future<void> crateApiPlayerPlayerStop({required PlatformInt64 playerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(playerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerStopConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "player_stop", argNames: ["playerId"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PlayerEvent(
      kind: dco_decode_player_event_kind(arr[0]),
      positionMs: dco_decode_i_64(arr[1]),
      durationMs: dco_decode_i_64(arr[2]),
      width: dco_decode_i_32(arr[3]),
      height: dco_decode_i_32(arr[4]),
      bufferingPercent: dco_decode_i_32(arr[5]),
      state: dco_decode_player_state(arr[6]),
      message: dco_decode_String(arr[7]),
    );
  }

  @protected
  PlayerEventKind dco_decode_player_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerEventKind.values[raw as int];
  }

  @protected
  PlayerHandle dco_decode_player_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlayerHandle(
      playerId: dco_decode_i_64(arr[0]),
      textureId: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerState.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_player_event_kind(deserializer);
    var var_positionMs = sse_decode_i_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    var var_bufferingPercent = sse_decode_i_32(deserializer);
    var var_state = sse_decode_player_state(deserializer);
    var var_message = sse_decode_String(deserializer);
    return PlayerEvent(
      kind: var_kind,
      positionMs: var_positionMs,
      durationMs: var_durationMs,
      width: var_width,
      height: var_height,
      bufferingPercent: var_bufferingPercent,
      state: var_state,
      message: var_message,
    );
  }

  @protected
  PlayerEventKind sse_decode_player_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerEventKind.values[inner];
  }

  @protected
  PlayerHandle sse_decode_player_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playerId = sse_decode_i_64(deserializer);
    var var_textureId = sse_decode_i_64(deserializer);
    return PlayerHandle(playerId: var_playerId, textureId: var_textureId);
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerState.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_player_event_kind(self.kind, serializer);
    sse_encode_i_64(self.positionMs, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
    sse_encode_i_32(self.bufferingPercent, serializer);
    sse_encode_player_state(self.state, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_player_event_kind(
    PlayerEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_player_handle(PlayerHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.playerId, serializer);
    sse_encode_i_64(self.textureId, serializer);
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
