// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'player_events.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AspectRatioMode dco_decode_aspect_ratio_mode(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MediaSourceDto dco_decode_box_autoadd_media_source_dto(dynamic raw);

  @protected
  VideoOrientationConfig dco_decode_box_autoadd_video_orientation_config(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<MediaTrack> dco_decode_list_media_track(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaSourceDto dco_decode_media_source_dto(dynamic raw);

  @protected
  MediaTrack dco_decode_media_track(dynamic raw);

  @protected
  PipelineCapabilitiesDto dco_decode_pipeline_capabilities_dto(dynamic raw);

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw);

  @protected
  PlayerEventKind dco_decode_player_event_kind(dynamic raw);

  @protected
  PlayerHandle dco_decode_player_handle(dynamic raw);

  @protected
  PlayerState dco_decode_player_state(dynamic raw);

  @protected
  TrackType dco_decode_track_type(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoMetadata dco_decode_video_metadata(dynamic raw);

  @protected
  VideoOrientationConfig dco_decode_video_orientation_config(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AspectRatioMode sse_decode_aspect_ratio_mode(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MediaSourceDto sse_decode_box_autoadd_media_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  VideoOrientationConfig sse_decode_box_autoadd_video_orientation_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<MediaTrack> sse_decode_list_media_track(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaSourceDto sse_decode_media_source_dto(SseDeserializer deserializer);

  @protected
  MediaTrack sse_decode_media_track(SseDeserializer deserializer);

  @protected
  PipelineCapabilitiesDto sse_decode_pipeline_capabilities_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer);

  @protected
  PlayerEventKind sse_decode_player_event_kind(SseDeserializer deserializer);

  @protected
  PlayerHandle sse_decode_player_handle(SseDeserializer deserializer);

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer);

  @protected
  TrackType sse_decode_track_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoMetadata sse_decode_video_metadata(SseDeserializer deserializer);

  @protected
  VideoOrientationConfig sse_decode_video_orientation_config(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aspect_ratio_mode(
    AspectRatioMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_source_dto(
    MediaSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_video_orientation_config(
    VideoOrientationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_track(
    List<MediaTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_source_dto(
    MediaSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_track(MediaTrack self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_capabilities_dto(
    PipelineCapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_player_event_kind(
    PlayerEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_handle(PlayerHandle self, SseSerializer serializer);

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer);

  @protected
  void sse_encode_track_type(TrackType self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_metadata(VideoMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_video_orientation_config(
    VideoOrientationConfig self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
