// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A flat event struct pushed to Dart over a broadcast stream.
///
/// Modeled as a struct (rather than a data-carrying enum) so the generated Dart
/// bindings stay dependency-free (no `freezed`). Only the fields relevant to
/// `kind` are populated; others hold defaults.
class PlayerEvent {
  final PlayerEventKind kind;

  /// Milliseconds (for `PositionChanged`).
  final PlatformInt64 positionMs;

  /// Milliseconds (for `DurationChanged`).
  final PlatformInt64 durationMs;

  /// Pixels (for `VideoSize`).
  final int width;

  /// Pixels (for `VideoSize`).
  final int height;

  /// 0-100 (for `Buffering`).
  final int bufferingPercent;

  /// New state (for `StateChanged`).
  final PlayerState state;

  /// Human-readable message (for `Error`).
  final String message;

  const PlayerEvent({
    required this.kind,
    required this.positionMs,
    required this.durationMs,
    required this.width,
    required this.height,
    required this.bufferingPercent,
    required this.state,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      bufferingPercent.hashCode ^
      state.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          width == other.width &&
          height == other.height &&
          bufferingPercent == other.bufferingPercent &&
          state == other.state &&
          message == other.message;
}

/// Discriminates which fields of [`PlayerEvent`] are meaningful.
enum PlayerEventKind {
  durationChanged,
  positionChanged,
  videoSize,
  stateChanged,
  buffering,
  eos,
  error,
}

/// High-level playback state reported to Dart.
enum PlayerState {
  idle,
  ready,
  buffering,
  playing,
  paused,
  stopped,
  completed,
  error,
}
