// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'player_events.freezed.dart';

enum AspectRatioMode { fit, fill, stretch }

@freezed
sealed class MediaSourceDto with _$MediaSourceDto {
  const MediaSourceDto._();

  const factory MediaSourceDto.uri(String field0) = MediaSourceDto_Uri;
  const factory MediaSourceDto.flutterAsset(String field0) =
      MediaSourceDto_FlutterAsset;
}

/// Audio, video, or subtitle stream inside the current media.
class MediaTrack {
  final int id;
  final TrackType trackType;
  final String language;
  final String label;
  final bool selected;

  const MediaTrack({
    required this.id,
    required this.trackType,
    required this.language,
    required this.label,
    required this.selected,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      trackType.hashCode ^
      language.hashCode ^
      label.hashCode ^
      selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          trackType == other.trackType &&
          language == other.language &&
          label == other.label &&
          selected == other.selected;
}

/// A flat event struct pushed to Dart over a broadcast stream.
class PlayerEvent {
  final PlayerEventKind kind;
  final PlatformInt64 positionMs;
  final PlatformInt64 durationMs;
  final int width;
  final int height;
  final int bufferingPercent;
  final PlayerState state;
  final String message;
  final double fps;
  final int pixelAspectWidth;
  final int pixelAspectHeight;
  final int displayAspectWidth;
  final int displayAspectHeight;
  final bool interlaced;
  final String colorMatrix;
  final String colorRange;
  final String hdrFormat;
  final bool isSeekable;

  const PlayerEvent({
    required this.kind,
    required this.positionMs,
    required this.durationMs,
    required this.width,
    required this.height,
    required this.bufferingPercent,
    required this.state,
    required this.message,
    required this.fps,
    required this.pixelAspectWidth,
    required this.pixelAspectHeight,
    required this.displayAspectWidth,
    required this.displayAspectHeight,
    required this.interlaced,
    required this.colorMatrix,
    required this.colorRange,
    required this.hdrFormat,
    required this.isSeekable,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      bufferingPercent.hashCode ^
      state.hashCode ^
      message.hashCode ^
      fps.hashCode ^
      pixelAspectWidth.hashCode ^
      pixelAspectHeight.hashCode ^
      displayAspectWidth.hashCode ^
      displayAspectHeight.hashCode ^
      interlaced.hashCode ^
      colorMatrix.hashCode ^
      colorRange.hashCode ^
      hdrFormat.hashCode ^
      isSeekable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          width == other.width &&
          height == other.height &&
          bufferingPercent == other.bufferingPercent &&
          state == other.state &&
          message == other.message &&
          fps == other.fps &&
          pixelAspectWidth == other.pixelAspectWidth &&
          pixelAspectHeight == other.pixelAspectHeight &&
          displayAspectWidth == other.displayAspectWidth &&
          displayAspectHeight == other.displayAspectHeight &&
          interlaced == other.interlaced &&
          colorMatrix == other.colorMatrix &&
          colorRange == other.colorRange &&
          hdrFormat == other.hdrFormat &&
          isSeekable == other.isSeekable;
}

/// Discriminates which fields of [`PlayerEvent`] are meaningful.
enum PlayerEventKind {
  durationChanged,
  positionChanged,
  videoSize,
  stateChanged,
  buffering,
  eos,
  error,
  tracksChanged,
  metadataChanged,
}

/// High-level playback state reported to Dart.
enum PlayerState {
  idle,
  ready,
  buffering,
  playing,
  paused,
  stopped,
  completed,
  error,
}

enum TrackType { audio, video, subtitle }

/// Decoded video metadata surfaced to Dart.
class VideoMetadata {
  final int width;
  final int height;
  final double fps;
  final int pixelAspectWidth;
  final int pixelAspectHeight;
  final int displayAspectWidth;
  final int displayAspectHeight;
  final bool interlaced;
  final String colorMatrix;
  final String colorRange;
  final String hdrFormat;

  const VideoMetadata({
    required this.width,
    required this.height,
    required this.fps,
    required this.pixelAspectWidth,
    required this.pixelAspectHeight,
    required this.displayAspectWidth,
    required this.displayAspectHeight,
    required this.interlaced,
    required this.colorMatrix,
    required this.colorRange,
    required this.hdrFormat,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fps.hashCode ^
      pixelAspectWidth.hashCode ^
      pixelAspectHeight.hashCode ^
      displayAspectWidth.hashCode ^
      displayAspectHeight.hashCode ^
      interlaced.hashCode ^
      colorMatrix.hashCode ^
      colorRange.hashCode ^
      hdrFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoMetadata &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fps == other.fps &&
          pixelAspectWidth == other.pixelAspectWidth &&
          pixelAspectHeight == other.pixelAspectHeight &&
          displayAspectWidth == other.displayAspectWidth &&
          displayAspectHeight == other.displayAspectHeight &&
          interlaced == other.interlaced &&
          colorMatrix == other.colorMatrix &&
          colorRange == other.colorRange &&
          hdrFormat == other.hdrFormat;
}

/// Video flip/rotate configuration for Dart.
class VideoOrientationConfig {
  final bool flipHorizontal;
  final bool flipVertical;
  final int rotateDegrees;

  const VideoOrientationConfig({
    required this.flipHorizontal,
    required this.flipVertical,
    required this.rotateDegrees,
  });

  @override
  int get hashCode =>
      flipHorizontal.hashCode ^ flipVertical.hashCode ^ rotateDegrees.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoOrientationConfig &&
          runtimeType == other.runtimeType &&
          flipHorizontal == other.flipHorizontal &&
          flipVertical == other.flipVertical &&
          rotateDegrees == other.rotateDegrees;
}
