import 'package:flutter/material.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';

part 'video_controls_theme.g.theme.dart';

/// Visual styling for the built-in video control bar.
///
/// Register an instance in `ThemeData.extensions` to customize the controls, or
/// rely on the built-in [VideoControlsTheme.material] / [VideoControlsTheme.cupertino]
/// presets that the controls fall back to when no extension is provided.
///
/// `copyWith`, `lerp`, `==` and `hashCode` are generated by
/// `theme_extensions_builder` (see `video_controls_theme.g.theme.dart`).
@ThemeExtensions()
class VideoControlsTheme extends ThemeExtension<VideoControlsTheme>
    with _$VideoControlsTheme {
  const VideoControlsTheme({
    required this.iconColor,
    required this.activeIconColor,
    required this.activeTrackColor,
    required this.inactiveTrackColor,
    required this.bufferedTrackColor,
    required this.thumbColor,
    required this.textColor,
    required this.backgroundColor,
    required this.primaryIconSize,
    required this.secondaryIconSize,
    required this.barPadding,
    required this.borderRadius,
  });

  /// Material-styled preset (filled icons, wide slider, translucent scrim).
  factory VideoControlsTheme.material() => const VideoControlsTheme(
    iconColor: Color(0xFFFFFFFF),
    activeIconColor: Color(0xFF82B1FF),
    activeTrackColor: Color(0xFFFFFFFF),
    inactiveTrackColor: Color(0x4DFFFFFF),
    bufferedTrackColor: Color(0x80FFFFFF),
    thumbColor: Color(0xFFFFFFFF),
    textColor: Color(0xFFFFFFFF),
    backgroundColor: Color(0x99000000),
    primaryIconSize: 24,
    secondaryIconSize: 24,
    barPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 8),
    borderRadius: 0,
  );

  /// iOS-styled preset (thin track, rounded translucent bar, SF-like sizing).
  factory VideoControlsTheme.cupertino() => const VideoControlsTheme(
    iconColor: Color(0xFFFFFFFF),
    activeIconColor: Color(0xFFFFFFFF),
    activeTrackColor: Color(0xFFFFFFFF),
    inactiveTrackColor: Color(0x3DFFFFFF),
    bufferedTrackColor: Color(0x66FFFFFF),
    thumbColor: Color(0xFFFFFFFF),
    textColor: Color(0xFFEBEBF5),
    backgroundColor: Color(0x66000000),
    primaryIconSize: 24,
    secondaryIconSize: 22,
    barPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 10),
    borderRadius: 14,
  );

  /// Color of idle control icons.
  final Color iconColor;

  /// Color used to highlight active toggles (e.g. looping enabled).
  final Color activeIconColor;

  /// Played portion of the seek bar.
  final Color activeTrackColor;

  /// Unplayed portion of the seek bar.
  final Color inactiveTrackColor;

  /// Buffered-ahead portion of the seek bar.
  final Color bufferedTrackColor;

  /// Seek bar thumb color.
  final Color thumbColor;

  /// Position/duration label color.
  final Color textColor;

  /// Control bar / scrim background color.
  final Color backgroundColor;

  /// Size of the central play/pause icon.
  final double primaryIconSize;

  /// Size of secondary icons (mute, loop, speed, skip).
  final double secondaryIconSize;

  /// Padding around the bottom control bar.
  final EdgeInsets barPadding;

  /// Corner radius of the control bar background.
  final double borderRadius;
}
