// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../player.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_player`

/// Creates a new player and its backing Flutter texture.
///
/// `engine_handle` must be obtained on the Dart side via
/// `EngineContext.instance.getEngineHandle()`.
Future<PlayerHandle> createPlayer({required PlatformInt64 engineHandle}) =>
    RustLib.instance.api.crateApiPlayerCreatePlayer(engineHandle: engineHandle);

/// Subscribes to the player's event stream (state, position, duration, size,
/// buffering, EOS, errors). Should be called once right after `create_player`.
Stream<PlayerEvent> playerEventStream({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerEventStream(playerId: playerId);

/// Loads a media URI (`file://...`, `http(s)://...`, `rtsp://...`) and prerolls.
Future<void> playerSetSource({
  required PlatformInt64 playerId,
  required String uri,
}) => RustLib.instance.api.crateApiPlayerPlayerSetSource(
  playerId: playerId,
  uri: uri,
);

Future<void> playerPlay({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPlay(playerId: playerId);

Future<void> playerPause({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPause(playerId: playerId);

Future<void> playerStop({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerStop(playerId: playerId);

Future<void> playerSeek({
  required PlatformInt64 playerId,
  required PlatformInt64 positionMs,
}) => RustLib.instance.api.crateApiPlayerPlayerSeek(
  playerId: playerId,
  positionMs: positionMs,
);

Future<void> playerSetVolume({
  required PlatformInt64 playerId,
  required double volume,
}) => RustLib.instance.api.crateApiPlayerPlayerSetVolume(
  playerId: playerId,
  volume: volume,
);

Future<void> playerSetMute({
  required PlatformInt64 playerId,
  required bool mute,
}) => RustLib.instance.api.crateApiPlayerPlayerSetMute(
  playerId: playerId,
  mute: mute,
);

Future<void> playerSetSpeed({
  required PlatformInt64 playerId,
  required double speed,
}) => RustLib.instance.api.crateApiPlayerPlayerSetSpeed(
  playerId: playerId,
  speed: speed,
);

Future<void> playerSetLooping({
  required PlatformInt64 playerId,
  required bool looping,
}) => RustLib.instance.api.crateApiPlayerPlayerSetLooping(
  playerId: playerId,
  looping: looping,
);

Future<PlatformInt64> playerPosition({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPosition(playerId: playerId);

Future<PlatformInt64> playerDuration({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerDuration(playerId: playerId);

/// Tears down the player, stops the pipeline and releases the texture.
Future<void> disposePlayer({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerDisposePlayer(playerId: playerId);

/// Identifiers returned when a player is created. `texture_id` is passed to the
/// Flutter `Texture` widget; `player_id` addresses all further control calls.
class PlayerHandle {
  final PlatformInt64 playerId;
  final PlatformInt64 textureId;

  const PlayerHandle({required this.playerId, required this.textureId});

  @override
  int get hashCode => playerId.hashCode ^ textureId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerHandle &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId &&
          textureId == other.textureId;
}
