// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../player_events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_player`

/// Creates a new GStreamer-backed player.
Future<PlayerHandle> createPlayer() =>
    RustLib.instance.api.crateApiPlayerCreatePlayer();

/// macOS: synchronously records the NSView handle for bus sync / rebind.
Future<void> cacheMacosOverlayHandle({
  required PlatformInt64 playerId,
  required PlatformInt64 viewPtr,
}) => RustLib.instance.api.crateApiPlayerCacheMacosOverlayHandle(
  playerId: playerId,
  viewPtr: viewPtr,
);

/// macOS: applies the cached NSView handle to the GStreamer sink (main thread).
Future<void> applyMacosOverlayGstreamer({
  required PlatformInt64 playerId,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPlayerApplyMacosOverlayGstreamer(
  playerId: playerId,
  width: width,
  height: height,
);

/// macOS: records the target `NSView` handle (apply via Swift main-thread dispatch).
Future<void> syncMacosVideoLayer({
  required PlatformInt64 playerId,
  required PlatformInt64 viewPtr,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPlayerSyncMacosVideoLayer(
  playerId: playerId,
  viewPtr: viewPtr,
  width: width,
  height: height,
);

/// Binds a native window/surface handle to the player's VideoOverlay sink.
Future<void> setVideoOverlayWindow({
  required PlatformInt64 playerId,
  required PlatformInt64 windowHandle,
}) => RustLib.instance.api.crateApiPlayerSetVideoOverlayWindow(
  playerId: playerId,
  windowHandle: windowHandle,
);

Future<void> notifyAndroidSurface({
  required PlatformInt64 playerId,
  required PlatformInt64 handle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPlayerNotifyAndroidSurface(
  playerId: playerId,
  handle: handle,
  width: width,
  height: height,
);

/// Subscribes to the player's event stream (state, position, duration, size,
/// buffering, EOS, errors). Should be called once right after `create_player`.
Stream<PlayerEvent> playerEventStream({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerEventStream(playerId: playerId);

/// Loads media from a unified source descriptor (URI or Flutter asset).
Future<void> playerLoadSource({
  required PlatformInt64 playerId,
  required MediaSourceDto source,
  required bool autoPlay,
}) => RustLib.instance.api.crateApiPlayerPlayerLoadSource(
  playerId: playerId,
  source: source,
  autoPlay: autoPlay,
);

/// Loads a media URI (`file://...`, `http(s)://...`, `rtsp://...`) and prerolls.
Future<void> playerSetSource({
  required PlatformInt64 playerId,
  required String uri,
}) => RustLib.instance.api.crateApiPlayerPlayerSetSource(
  playerId: playerId,
  uri: uri,
);

/// Loads a Flutter asset key via AppSrc (no Dart-side temp file copy).
Future<void> playerSetAssetSource({
  required PlatformInt64 playerId,
  required String assetKey,
}) => RustLib.instance.api.crateApiPlayerPlayerSetAssetSource(
  playerId: playerId,
  assetKey: assetKey,
);

Future<void> playerPlay({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPlay(playerId: playerId);

Future<void> playerPause({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPause(playerId: playerId);

Future<void> playerStop({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerStop(playerId: playerId);

Future<void> playerSeek({
  required PlatformInt64 playerId,
  required PlatformInt64 positionMs,
}) => RustLib.instance.api.crateApiPlayerPlayerSeek(
  playerId: playerId,
  positionMs: positionMs,
);

Future<void> playerSetVolume({
  required PlatformInt64 playerId,
  required double volume,
}) => RustLib.instance.api.crateApiPlayerPlayerSetVolume(
  playerId: playerId,
  volume: volume,
);

Future<void> playerSetMute({
  required PlatformInt64 playerId,
  required bool mute,
}) => RustLib.instance.api.crateApiPlayerPlayerSetMute(
  playerId: playerId,
  mute: mute,
);

Future<void> playerSetSpeed({
  required PlatformInt64 playerId,
  required double speed,
}) => RustLib.instance.api.crateApiPlayerPlayerSetSpeed(
  playerId: playerId,
  speed: speed,
);

Future<void> playerSetLooping({
  required PlatformInt64 playerId,
  required bool looping,
}) => RustLib.instance.api.crateApiPlayerPlayerSetLooping(
  playerId: playerId,
  looping: looping,
);

Future<PlatformInt64> playerPosition({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerPosition(playerId: playerId);

Future<PlatformInt64> playerDuration({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerDuration(playerId: playerId);

Future<bool> playerIsSeekable({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerIsSeekable(playerId: playerId);

Future<PipelineCapabilitiesDto> playerGetPipelineCapabilities({
  required PlatformInt64 playerId,
}) => RustLib.instance.api.crateApiPlayerPlayerGetPipelineCapabilities(
  playerId: playerId,
);

Future<void> syncVideoOverlayRectangle({
  required PlatformInt64 playerId,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPlayerSyncVideoOverlayRectangle(
  playerId: playerId,
  width: width,
  height: height,
);

Future<List<MediaTrack>> playerGetTracks({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerGetTracks(playerId: playerId);

Future<void> playerSelectTrack({
  required PlatformInt64 playerId,
  required int trackId,
  required TrackType trackType,
  required bool enable,
}) => RustLib.instance.api.crateApiPlayerPlayerSelectTrack(
  playerId: playerId,
  trackId: trackId,
  trackType: trackType,
  enable: enable,
);

Future<VideoMetadata> playerGetVideoMetadata({
  required PlatformInt64 playerId,
}) => RustLib.instance.api.crateApiPlayerPlayerGetVideoMetadata(
  playerId: playerId,
);

Future<void> playerSetVideoOrientation({
  required PlatformInt64 playerId,
  required VideoOrientationConfig config,
}) => RustLib.instance.api.crateApiPlayerPlayerSetVideoOrientation(
  playerId: playerId,
  config: config,
);

Future<void> playerSetAspectRatioMode({
  required PlatformInt64 playerId,
  required AspectRatioMode mode,
}) => RustLib.instance.api.crateApiPlayerPlayerSetAspectRatioMode(
  playerId: playerId,
  mode: mode,
);

/// Tears down the player and stops the pipeline.
Future<void> disposePlayer({required PlatformInt64 playerId}) =>
    RustLib.instance.api.crateApiPlayerDisposePlayer(playerId: playerId);

/// Identifiers returned when a player is created. `player_id` addresses all
/// control calls; bind a Platform View with the same id via `creationParams`.
class PlayerHandle {
  final PlatformInt64 playerId;

  const PlayerHandle({required this.playerId});

  @override
  int get hashCode => playerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerHandle &&
          runtimeType == other.runtimeType &&
          playerId == other.playerId;
}
